title: Enkhjargal Lkhagvaa
subtitle: "Digital Marketing & Software Professional"
description: >
  Expertise in driving brand growth through data-driven insights,
  supported by software development experience
  and Google-certified digital marketing skills.

plugins:
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false
